### ISSUE TITLE
Update documentation on redis properties

### ISSUE THREAD

**Issue by moarsoarse** [structurizr/structurizr.github.io#25]
### Expected

as of latest updates property `structurizr.redis.database` becomes **required**

### Actual

in documents there is no information about `structurizr.redis.database`

### Steps to reproduce

just don't provide `structurizr.redis.database` upon startup

### Version/build information

3.1.0

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

### More information

Add proper description to 07-http-sessions.md

**Comment by simonbrowndotje** [comment]
Apologies - I didn't commit the docs changes after the build! 😂
