### ISSUE TITLE
tree-sitter grammar for Structurizr DSL

### ISSUE THREAD

**Issue by josteink** [structurizr/structurizr.github.io#26]
### Description

There was demand for a Structurizr DSL tree-sitter grammar (ref https://github.com/structurizr/dsl/issues/200).

I'm trying to implement support for Strucurizr DSL in Emacs too, and thought this would be useful to have.

In that regard I've started developing a grammar here: https://github.com/josteink/tree-sitter-structurizr

Currently supported grammar and how they are parsed can be seen in the test file: https://github.com/josteink/tree-sitter-structurizr/blob/master/test/corpus/test.txt

I'm OK with developing this as a 3rd party, but if someone wants to link to it, or help out, or make more official... I'm all open to those options.

I'll be around. Let me know what you think!

### Priority

I'm willing to add this feature myself and raise a PR (please confirm approach first)

**Comment by simonbrowndotje** [comment]
Thanks - I've added a link from the community tooling page.

**Comment by josteink** [comment]
Thanks! Glad to be of service!
